name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  external-dns_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.external-dns_version.outputs.version }}
      gh_tag: ${{ steps.external-dns_version.outputs.gh_tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Get external-dns version
        id: external-dns_version
        run: |
          GH_TAG=$(go list -f '{{ .Version }}' -m 'sigs.k8s.io/external-dns')
          VERSION=$(go list -f '{{ .Version }}' -m 'sigs.k8s.io/external-dns' | sed -E 's/v?(.+)/\1/')
          echo $GH_TAG $VERSION
          echo "::set-output name=version::${VERSION}"
          echo "::set-output name=gh_tag::${GH_TAG}"
  docker:
    runs-on: ubuntu-latest
    needs: external-dns_version
    env:
      PLATFORMS: linux/amd64,linux/arm64/v8,linux/arm/v7
      DOCKERHUB_USERNAME: isac322
    steps:
      - uses: actions/checkout@v3
        with:
          repository: kubernetes-sigs/external-dns
          ref: ${{ needs.external-dns_version.outputs.gh_tag }}
      - name: disable test
        run: sed -i -E 's/^\s*RUN\s+make\s+test\s+(build.*)$/RUN make \1/' Dockerfile.mini
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4.1.0
        with:
          flavor: latest=true
          images: ${{ env.DOCKERHUB_USERNAME }}/external-dns
          tags: |
            type=raw,value=${{ needs.external-dns_version.outputs.version }}
          labels: |
            maintainer=${{ env.DOCKERHUB_USERNAME }}
            org.opencontainers.image.title=external-dns
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.mini
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/external-dns:latest
          cache-to: type=inline
      - name: Update repo description
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKERHUB_USERNAME }}/external-dns
